### ISSUE TITLE
topology rule

### ISSUE THREAD

**Issue by Desalegn21** [Esri/arcgis-runtime-samples-android#104]
hi,guys ,i m new android developer using esri, i developed geometry editor  but  i left topology rule like polygons must not cross ,no gap between polygons,and polygons can be teach each other .any one can help me.

**Comment by shellygill** [comment]
Hi there - if you have questions about how to develop with the ArcGIS Runtime SDK for Android, you can go to the geonet forum at https://geonet.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android and ask them there.

This repo is for the samples in particular, so if you have any problems or suggestions for working with the samples in this repo, that's when you should add an issue.

**Comment by doneill** [comment]
@Desalegn21 Take a look at the [Geometry Sample](https://github.com/Esri/arcgis-runtime-samples-android/tree/master/GeometrySample) for examples of using the API with spatial relations.  If you have questions specific to a sample please post them here, otherwise as @shellygill said please post general ArcGIS Android SDK questions to our [geonet forum](https://geonet.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android).

Closing this issue as a **GeoNet Question**.
