### ISSUE TITLE
Quartz beta: reverse geocoding not returning full address

### ISSUE THREAD

**Issue by mlumeau** [Esri/arcgis-runtime-samples-android#150]
When calling a reverse geocoding from a `LocatorTask` object, the resulting `GeocodeResult` does not hold an address.
Here is the request:

        ReverseGeocodeParameters params = new ReverseGeocodeParameters();
        params.setMaxDistance(200.0);
        params.getResultAttributeNames().add("*");

        mLocatorResults =  mLocator.reverseGeocodeAsync(location, params);

And here is the first result:
```
topResult = {GeocodeResult@9885} 
    mAttributes = null
    mCoreGeocodeResult = {CoreGeocodeResult@9888} 
    mDisplayLocation = {Point@9886} "Point: [1.442894, 43.604383, 0.000000, NaN] "
    mExtent = null
    mInputLocation = null
    mRouteLocation = null
    shadow$_klass_ = {Class@5184} "class com.esri.arcgisruntime.tasks.geocode.GeocodeResult"
    shadow$_monitor_ = -1942673134
```
We can see that the mAttributes field is null. Furthermore, `getAttributes()` will return a map of null objects.

I can still get the address by calling `getLabel()` that returns the postal address, though.

**Comment by willcrick** [comment]
@mlumeau thanks for this info, it is difficult to work out what is going on here without information on the service/locator you are using. If the issue is not related to a sample in this repo, it might be best dealt with on the beta forum: https://earlyadopter.esri.com/project/forum/topic.html?cap=48D60A7369424E8FAB77D13C082D75A8&forid={BD7E9065-FDF7-4633-A5FE-6609BE7AD936}
