### ISSUE TITLE
migrate to 100.0.0

### ISSUE THREAD

**Issue by MFV96** [Esri/arcgis-runtime-samples-android#303]
hi.i want migrate to 100.0 from 10.8 .
but when i use some of attribute i have error. i want use some of old version attribute vs new attribute.
why i have error!!! how i can fix it??\

**Comment by shellygill** [comment]
Hi Mashid - 100.0 is different in many areas to 10.2.8, although most concepts are pretty much the same. If you're talking about the map attributes such as `mapoptions.MapType="Streets",   mapoptions.center="34.056215, -117.195668", mapoptions.ZoomLevel="16"`` set in layout XML, they are not available in 100.0; however you can easily add basemaps, and set the initial extent (`MapView.setViewpoint` in 100.0) in code. You might find the following useful:
 - https://developers.arcgis.com/android/latest/guide/migrate-to-100-0-0.htm
 - https://developers.arcgis.com/android/latest/guide/build-a-new-map.htm#ESRI_SECTION1_295A59B9BDD94A318611EA60F9A29EBC
 - https://developers.arcgis.com/android/latest/guide/display-a-map.htm#ESRI_SECTION1_5E4F4F6A4D4B44EFB53258B6D53CFD3B

If you have specific problems with or enhancement requests for the samples in this repo, please go ahead and submit issues. Otherwise, this kind of question is best asked on the GeoNet community at https://geonet.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android.
