### ISSUE TITLE
Offline editor Sample - can't popup the attributes 

### ISSUE THREAD

**Issue by carlosrishmawi** [Esri/arcgis-runtime-samples-android#37]
after disconnected/ switched offline, it's not possible to edit or change the attributes for any point, line or polygon in the feature service, as it was in the older API sample..

.

**Comment by doneill** [comment]
@carlosrishmawi Thanks for logging this issue.  I will look into our previous release of this sample to see if we can get it re-implemented.

**Comment by carlosrishmawi** [comment]
Did you have the chance to look at the attribute editing issue ???

**Comment by doneill** [comment]
@carlosrishmawi Yes I have and will be working on it soon, hope to have it included with our upcoming samples update release.

**Comment by doneill** [comment]
@carlosrishmawi We have identified the original code that supported opening a Popup to edit attributes.  We removed this from the sample in order to simplify it, we will research re-introducing back into our current sample implementation.  While we are doing that, have you looked at our [Popup for Editing](https://github.com/Esri/arcgis-runtime-samples-android/tree/master/PopupInWebMapForEditing) sample?  That sample is similar to the implementation we had originally in this sample, only now we are working with ```FeatureTable```s.  Let me know if that sample helps you in the near term.
