### ISSUE TITLE
[Question] how can i add two baseLayer display together?

### ISSUE THREAD

**Issue by parcool** [Esri/arcgis-runtime-samples-android#430]
I can't find the sample for add two base layer display together.
I have to display two layer in a mapView which one is the world layer and the another is a city base layer,they must show together and the city layer z-index is higher than the world layer.how can i do it?

**Comment by parcool** [comment]
note:the world layer is WMTS and city layer is WFS

**Comment by shellygill** [comment]
Hi @parcool - we do not have a sample for this. Just create the layers and then add them to the Basemap LayerList - e.g. `map.getBasemap().getBaseLayers().add(theLayer)`.  We currently support WMTS (https://developers.arcgis.com/android/latest/api-reference/reference/com/esri/arcgisruntime/layers/WmtsLayer.html) but do not currently support WFS services as layers.

If you have specific problems with or enhancement requests for the samples in this repo, please go ahead and submit issues. Otherwise, this kind of question is best asked on the GeoNet community at https://geonet.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android.
